// Autogenerated from slangmosh, do not edit.
#ifndef SLANGMOSH_GENERATED_FFmpegEncodeiface_H
#define SLANGMOSH_GENERATED_FFmpegEncodeiface_H
#include <stdint.h>
namespace Vulkan
{
class Program;
class Shader;
}

namespace FFmpegEncode
{
template <typename Program = Vulkan::Program *, typename Shader = Vulkan::Shader *>
struct Shaders
{
	Program rgb_to_yuv = {};
	Program rgb_scale = {};
	Program chroma_downsample = {};
	Shaders() = default;

	template <typename Device, typename Layout, typename Resolver>
	Shaders(Device &device, Layout &layout, const Resolver &resolver);
};
}
#endif
