// Autogenerated from slangmosh, do not edit.
#ifndef SLANGMOSH_GENERATED_FFmpegDecodeiface_H
#define SLANGMOSH_GENERATED_FFmpegDecodeiface_H
#include <stdint.h>
namespace Vulkan
{
class Program;
class Shader;
}

namespace FFmpegDecode
{
template <typename Program = Vulkan::Program *, typename Shader = Vulkan::Shader *>
struct Shaders
{
	Program yuv_to_rgb = {};
	Shaders() = default;

	template <typename Device, typename Layout, typename Resolver>
	Shaders(Device &device, Layout &layout, const Resolver &resolver);
};
}
#endif
