#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
layout(local_size_x = 1, local_size_y = 1) in;

layout(std430, binding = 0, set = 0) buffer SSBO
{
    f16vec4 a;
    f16vec4 b;
    float16_t dot_result;
    float16_t length_a_result;
    float16_t length_b_result;
    float16_t distance_result;
};

void main()
{
    dot_result = dot(a, b);
    length_a_result = length(a);
    length_b_result = length(b);
    distance_result = distance(a, b);
}