#version 450
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

layout(rgba8, set = 0, binding = 0) uniform image3D uImg;
layout(constant_id = 3) const bool RMW = false;

void main()
{
    vec4 loaded = vec4(0.0);

    if (RMW)
        loaded = 0.01 * imageLoad(uImg, ivec3(gl_GlobalInvocationID));

    loaded += sin(vec4(0, 1, 2, 3) + 0.15 * vec3(gl_GlobalInvocationID).xyzz);

    imageStore(uImg, ivec3(gl_GlobalInvocationID), loaded);
}