#version 450
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

layout(local_size_x = 1) in;

layout(set = 0, binding = 0) readonly buffer A
{
    ivec4 a, b;
};

layout(set = 0, binding = 1) writeonly buffer B
{
    i16vec4 c, d;
};

layout(set = 1, binding = 0) uniform UBO
{
    int e;
};

void main()
{
    i16vec4 tmp0 = i16vec4(a >> 16);
    i16vec4 tmp1 = i16vec4(b >> 16);
    i16vec4 tmp2 = i16vec4(e << 1);
    tmp0 = min(tmp0, tmp2);
    tmp1 = max(tmp1, tmp2);
    c = tmp0;
    d = tmp1;
}