#version 460
#extension GL_EXT_ray_query : require
#extension GL_EXT_ray_flags_primitive_culling : require
layout(primitive_culling);
layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) uniform accelerationStructureEXT uAS;
layout(set = 0, binding = 1) writeonly uniform image2D uImage;

void main()
{
    rayQueryEXT q;

    vec3 origin = vec3(0.0, 0.0, 5.0);
    vec3 dir = vec3(2.0 * vec2(gl_GlobalInvocationID.xy) / 512.0 - 1.0, -1.0);
    rayQueryInitializeEXT(q, uAS, gl_RayFlagsOpaqueEXT | gl_RayFlagsSkipAABBEXT, 0xff, origin, 0.1, dir, 10.0);

    rayQueryProceedEXT(q);

    vec4 color = vec4(0.21, 0.02, 0.03, 1.0);
    if (rayQueryGetIntersectionTypeEXT(q, true) == gl_RayQueryCommittedIntersectionTriangleEXT)
    {
        color.r = float(rayQueryGetIntersectionGeometryIndexEXT(q, true));
        color.g = float(rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT(q, true));
        color.b = float(rayQueryGetIntersectionInstanceCustomIndexEXT(q, true)) / 255.0;
    }

    imageStore(uImage, ivec2(gl_GlobalInvocationID.xy), color);
}