#version 450
layout(local_size_x = 64) in;

layout(set = 0, binding = 0) uniform sampler2D uTexture;

layout(set = 0, binding = 1) writeonly buffer uBuffer
{
    uvec2 samples[];
};

void main()
{
    float u = float(gl_GlobalInvocationID.x) / (4.0 * 2048.0);

    float gather_result = textureGather(uTexture, vec2(u, 0.5), 0).x;
    float point_result = textureLod(uTexture, vec2(u, 0.5), 0.0).x;
    samples[gl_GlobalInvocationID.x] = uvec2(round(255.0 * vec2(point_result, gather_result)));
}