#version 450
layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) writeonly uniform image2D SwapImage;

layout(push_constant) uniform Registers
{
    uvec2 resolution;
} registers;

void main()
{
    if (all(lessThan(gl_GlobalInvocationID.xy, registers.resolution)))
    {
        uint checker = (gl_GlobalInvocationID.x ^ gl_GlobalInvocationID.y) >> 6u;
        imageStore(SwapImage, ivec2(gl_GlobalInvocationID.xy), (checker & 1u) != 0u ? vec4(0.6, 0.1, 0.1, 1.0) : vec4(0.1, 0.6, 0.1, 1.0));
    }
}