#ifndef GLOBAL_BINDINGS_H_
#define GLOBAL_BINDINGS_H_

#define BINDING_GLOBAL_TRANSFORM 0
#define BINDING_GLOBAL_RENDER_PARAMETERS 1
#define BINDING_GLOBAL_ENV_RADIANCE 2
#define BINDING_GLOBAL_ENV_IRRADIANCE 3
#define BINDING_GLOBAL_BRDF_TABLE 4
#define BINDING_GLOBAL_DIRECTIONAL_SHADOW 5
#define BINDING_GLOBAL_AMBIENT_OCCLUSION 6
#define BINDING_GLOBAL_VOLUMETRIC_FOG 7

#define BINDING_GLOBAL_CLUSTERER_PARAMETERS 8
#define BINDING_GLOBAL_CLUSTER_IMAGE_LEGACY 9
#define BINDING_GLOBAL_CLUSTER_SPOT_LEGACY 10
#define BINDING_GLOBAL_CLUSTER_POINT_LEGACY 11
#define BINDING_GLOBAL_CLUSTER_LIST_LEGACY 12

#define BINDING_GLOBAL_CLUSTER_TRANSFORM 9
#define BINDING_GLOBAL_CLUSTER_BITMASK 10
#define BINDING_GLOBAL_CLUSTER_RANGE 11

#define BINDING_GLOBAL_LINEAR_SAMPLER 14
#define BINDING_GLOBAL_SHADOW_SAMPLER 15

#endif