#ifndef MESHLET_PAYLOAD_CONSTANTS_H_
#define MESHLET_PAYLOAD_CONSTANTS_H_

#define MESHLET_PAYLOAD_MAX_ELEMENTS 256
#define MESHLET_PAYLOAD_NUM_CHUNKS 8
#define MESHLET_PAYLOAD_MAX_STREAMS 16

const int MESHLET_STREAM_TYPE_PRIMITIVE = 0;
const int MESHLET_STREAM_TYPE_POSITION = 1;
const int MESHLET_STREAM_TYPE_NORMAL_TANGENT_OCT8 = 2;
const int MESHLET_STREAM_TYPE_UV = 3;
const int MESHLET_STREAM_TYPE_BONE_INDICES = 4;
const int MESHLET_STREAM_TYPE_BONE_WEIGHTS = 5;

#endif
