#ifndef MESHLET_PAYLOAD_CONSTANTS_H_
#define MESHLET_PAYLOAD_CONSTANTS_H_

#define MESHLET_PAYLOAD_MAX_THREADS 256
#define MESHLET_PAYLOAD_MAX_PRIMITIVES 256
#define MESHLET_PAYLOAD_MAX_VERTICES 128
#define MESHLET_PAYLOAD_PRIMITIVES_PER_CHUNK 64
#define MESHLET_PAYLOAD_VERTICES_PER_CHUNK 32
#define MESHLET_PAYLOAD_NUM_CHUNKS 4
#define MESHLET_PAYLOAD_MAX_STREAMS 8

const int MESHLET_STREAM_TYPE_PRIMITIVE = 0;
const int MESHLET_STREAM_TYPE_POSITION = 1;
const int MESHLET_STREAM_TYPE_NORMAL_TANGENT_OCT8 = 2;
const int MESHLET_STREAM_TYPE_UV = 3;
const int MESHLET_STREAM_TYPE_BONE_INDICES = 4;
const int MESHLET_STREAM_TYPE_BONE_WEIGHTS = 5;

#endif
